# Configuration de la source de données PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123

  # Configuration du dialecte Hibernate pour PostgreSQL
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    # Mode de création et de mise à jour de la base de données par Hibernate
    hibernate:
      ddl-auto: update
